### PR TITLE
Use cygpath to make activate work in Msys bash shells

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by msarahan** [comment]
Nice!  Does this handle cygwin in addition to Msys, or are there different uname strings to check?  I think most people these days use Msys stuff, but I want to make sure to help as many people as possible.

**Comment by maxnoe** [comment]
http://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux

Does cygwin has the same Problem with the paths? I never used it.

**Comment by maxnoe** [comment]
Oh shit.

According to wikipedia: https://en.wikipedia.org/wiki/Uname the `-o` option is not supported on several distributions, including all  MacOS versions.

So one would have to check the `uname -s` output, which has more varieties.

**Comment by maxnoe** [comment]
This might be helpful:
http://stackoverflow.com/a/8063398/3838691

**Comment by msarahan** [comment]
It looks to me like this kind of statement might catch all possibilities and work well:

http://stackoverflow.com/a/17072017/1170370

The earliest I can do this myself would be next week.  If you have time and want to hack further and test it, I would certainly appreciate it.

**Comment by maxnoe** [comment]
Please have a look into. I tested it on windows in a msys2 bash shell. Everything seems to work fine (activating / deactivating /installing new packages into the env)

**Comment by maxnoe** [comment]
Tested the new version now also on arch linux. Works fine.

**Comment by msarahan** [comment]
I haven't had time to test this.  The code looks sane.  If there are any issues I encounter with the PR later, I may ping you if I need help.  I'm merging this now.  I hope to get the PR in soon, but need to clear the move of the activate/deactivate scripts with the rest of the team.

Thanks for figuring this out.  People will be very appreciative.  I'll make sure this PR appears in the release notes somehow.

**Pull request merged**
